### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by patrickml** [LnsooXD/koa-socket.io#4]
I am currently getting this error

```sh
/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:13355
    return /*require.resolve*/(!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                               ^

Error: Cannot find module "."
    at webpackMissingModule (/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:13355:76)
    at resolvePath (/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:13355:154)
    at Server.serveClient (/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:13358:25)
    at new Server (/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:13297:8)
    at SocketServer.start (/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:13185:23)
    at Object.<anonymous> (/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:7014:4)
    at __webpack_require__ (/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:20:30)
    at Object.defineProperty.value (/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:6988:18)
    at __webpack_require__ (/Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:20:30)
    at /Users/patricklewis/Documents/sites/personal/tower/server/dist/index.js:63:18
```

Here is my code
```js
import Koa from 'koa';
import IO from 'koa-socket.io';
import http from 'http';

const app = new Koa();
const io = new IO({
  namespace: '/',
});

const server = http.createServer(app.callback());

io.start(server);

io.on('join', () => {
  console.log('join event receiverd, new user: ', this.data);

  // use global io send borad cast
  io.emit('msg', `[All]: ${this.data} joind`);

  // use current socket send a broadcast
  this.socket.broadcast('msg', `[All]: Hello guys, I'm ${this.data}.`);

  // just send to current user
  this.socket.emit('msg', `[${this.data}]  Welcome to koa-socket.io !`);
});

server.listen(process.env.PORT || 3001);

console.log('test');
```

My package.json
```js
{
  "name": "tower-server",
  "version": "0.0.1",
  "description": "Tower Server",
  "main": "src/index.js",
  "scripts": {
    "start": "webpack-watch-server",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Patrickml",
  "license": "ISC",
  "dependencies": {
    "bufferutil": "^3.0.2",
    "koa": "^2.3.0",
    "koa-socket.io": "^1.1.2",
    "socket.io": "^2.0.3",
    "utf-8-validate": "^3.0.3"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.24.1",
    "eslint": "^4.3.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.7.0",
    "jest": "^20.0.4",
    "nodemon": "^1.11.0",
    "webpack": "^3.3.0",
    "webpack-watch-server": "^1.1.0"
  }
}
```

**Comment by patrickml** [comment]
The issue seems to be that I have to add `var nodeExternals = require('webpack-node-externals');` and `externals: [nodeExternals()],`
